name: Deploy to Staging

on:
    push:
        branches:
            - staging # Changed from 'main'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Staging Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.STAGING_HOST }}
                  username: ${{ secrets.STAGING_USER }}
                  key: ${{ secrets.STAGING_SSH_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |
                      su - newuser << 'EOF'
                      export PATH=$PATH:/usr/bin:/usr/local/bin:$HOME/.nvm/versions/node/v*/bin

                      export NODE_OPTIONS="--max-old-space-size=768"
                      cd /var/www/common-scents/staging

                      git checkout staging
                      git pull origin staging

                      npm run install:all

                      npm run build:all

                      cd backend
                      pm2 restart ecosystem.config.js --update-env
